ALTER TABLE salles ADD COLUMN IF NOT EXISTS image VARCHAR(255) DEFAULT NULL;
ALTER TABLE salles ADD COLUMN IF NOT EXISTS capacite INT DEFAULT 0;
ALTER TABLE salles ADD COLUMN IF NOT EXISTS description TEXT DEFAULT NULL;

ALTER TABLE reservations ADD COLUMN IF NOT EXISTS statut ENUM('en_attente', 'approuvee', 'rejetee') DEFAULT 'en_attente';
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS raison_rejet TEXT DEFAULT NULL;
